### ISSUE TITLE
Kshitiz's wall question

### ISSUE THREAD

**Issue by brooklyn-omniheurists** [brooklyn-omniheurists/evasion#12]
Kshitiz asked
Hi,

How would the walls behave in the following scenario:
![diagram](http://i.imgur.com/iImx6Th.png)
What would happen at the last step? Would the horizontal wall extend to meet the new vertical wall or stay as is?

**Comment by brooklyn-omniheurists** [comment]
The walls aren't dependent on each other. What that means is that each wall has a start point, a direction, and an endpoint. the walls do not intersect and they do not depend on each other, deleting the wall placed @ 1 will have no affect on other walls.

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia

**Comment by KshitizSethia** [comment]
Close this please, my doubts stand answered :p
