### ISSUE TITLE
Scott's question (from wiki)

### ISSUE THREAD

**Issue by brooklyn-omniheurists** [brooklyn-omniheurists/evasion#13]
1) How is state communicated?

2) Will the opposing player be alerted with the commands of the other player? Or is it all using command 'P' and command 'W'? 

3) Can we call command 'P' and 'W' at any time (not count as a turn)? I'm a bit concerned because our state needs some concept of when the walls were built to know in how many turns the next wall will be built. Perhaps before each turn you could send location and wall info to both prey and hunter?

4) Can a hunter build a wall and delete a wall in the same move? If so, would that be two calls to the server, or just stuff it all in one JSON blob?

**Comment by brooklyn-omniheurists** [comment]
1. The publisher (port 1990) communicates all moves (state changes).
2. Opposing player is not alerted. Publisher communicates state and any further query can be made using "P" and "W".
3. "P" and "W" can be called any time. They are not considered a turn. A client can choose to cache everything the publisher sends but this is up to the client to implement.
4. Currently it is two calls and requires 2 steps. I need to fix the api to accept both building and deleting in the same move.

**Comment by mutaphore** [comment]
Can you explain what  you mean by opposing player is not alerted? I noticed that the hunter receives messages from the publisher but the prey doesn't. Is the prey expected to query the server continuously to get the latest state of game?

**Comment by brooklyn-omniheurists** [comment]
@mutaphore There is a publisher that broadcasts all moves to whoever is willing to listen. There is no direct communication to the player of such a move, but the player is free to ask the server for the latest updates at any time with the `P` and `W` commands!

What you noticed earlier was a bug we hadn't properly diagnosed, it should work now.
