### ISSUE TITLE
No move

### ISSUE THREAD

**Issue by mullachv** [brooklyn-omniheurists/evasion#14]
Is there a no move choice at any time for the Hunter? (Perhaps just build or destroy walls but not move)?
Similarly, can the Prey just not move at any of its opportunities to do so?

**Comment by brooklyn-omniheurists** [comment]
Hunter must move unfortunately, hunter remains on autopilot. Prey however has the option to not move.

**Comment by mullachv** [comment]
What is the CardinalDirection for No Move, I do not remember seeing one -

**Comment by brooklyn-omniheurists** [comment]
API documentation is coming soon, but its:

``` json
{ 
  "command": "M"
}
```

Yep, just leave direction out.

**Comment by brooklyn-omniheurists** [comment]
@mullachv yep, that should work 37761fd6161e2e73fdd72bbe6ebfe6ba8dc15ee6

**Comment by brooklyn-omniheurists** [comment]
https://github.com/brooklyn-omniheurists/evasion/blob/master/readme/API.md
