### ISSUE TITLE
Sample java client code

### ISSUE THREAD

**Issue by ghost** [brooklyn-omniheurists/evasion#15]
While trying to run the sample java client, the code gets stuck at (TyrusFuture.java:35) TyrosFuture.get() called at (ClientManager.java:189) ClientManager.connectToServer() called at (App.java:33) . Do you know a probable reason?
I am able to use test.html to connect to server and send commands

**Comment by brooklyn-omniheurists** [comment]
Can you close and reopen the server and then run the Java client? There may be an issue with a reset in the server I can look into.

**Comment by tnvkrishna** [comment]
Tried restarting the server and running the client. Still not able to connect.
