### ISSUE TITLE
cardinal Directions

### ISSUE THREAD

**Issue by jfriend08** [brooklyn-omniheurists/evasion#16]
Sorry, maybe I missed something. but why S is [0,1] ?
If this is the case, then if there is origin [0,0] and pointA [1,1], pointA is actually at low-right to origin?

```
var cardinalDirections = {
    N: [0,-1],
    S: [0,1],
    E: [1,0],
    W: [-1,0],
    NE: [1,-1],
    NW: [-1,-1],
    SE: [1,1],
    SW: [-1,1]
};
```

**Comment by brooklyn-omniheurists** [comment]
I'm sorry, we should've specified. [0, 0] is the top right corner of the screen. We will update the Readme to reflect that.

Y increases as it goes down, x remains the same.

**Comment by KshitizSethia** [comment]
@brooklyn-omniheurists: Do you mean [0,0] is top-left? Otherwise E and W do not make sense.

**Comment by KshitizSethia** [comment]
Here's a detailed picture denoting directions that I understand to be correct right now.
![camera_capture](https://cloud.githubusercontent.com/assets/4375768/10888246/0b3b143e-8159-11e5-87ce-873086202028.jpg)

Clarification:
1) The E(1,0) says: x coordinate will increase, but in the array we increase the second index. Is this correct/expected?

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia Yes I meant [0 0] is top left!

I don't understand the second question, i'm sorry!

**Comment by brooklyn-omniheurists** [comment]
Looks to be NAI
