### ISSUE TITLE
Server.js error message

### ISSUE THREAD

**Issue by QingxianLai** [brooklyn-omniheurists/evasion#17]
Hi architecture team, I used a python client to send messages to the server, and no matter what message I sent, the server will throw an error and close the websocket connection:

For example, at the beginning, the hunter client sent a message:
`{"command": "M"}`

And then the server stopped with an error:

```
/Users/LaiQX/Desktop/heuristic/archtectures/evasion/server.js:209
             connection1.send(JSON.stringify({
                        ^

TypeError: Cannot read property 'send' of null
    at sendMove (/Users/LaiQX/Desktop/heuristic/archtectures/evasion/server.js:209:25)
    at WebSocketConnection.<anonymous> (/Users/LaiQX/Desktop/heuristic/archtectures/evasion/server.js:82:13)
    at emitOne (events.js:77:13)
    at WebSocketConnection.emit (events.js:169:7)
    at WebSocketConnection.processFrame (/Users/LaiQX/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Users/LaiQX/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

Any thought about this?

**Comment by brooklyn-omniheurists** [comment]
Can you add a console.log on the message coming in and let me know what it prints out? Wondering if it's a json formatting issue.

**Comment by brooklyn-omniheurists** [comment]
Also is the test.html working for you?

**Comment by QingxianLai** [comment]
`console.log` print out this: `{ type: 'utf8', utf8Data: '{"command": "M"}' }`

and the test.html looks like this:
![screen shot 2015-11-01 at 1 19 45 am](https://cloud.githubusercontent.com/assets/8797643/10867410/c3e4295e-8036-11e5-9342-1fac88ca916f.png)

meanwhile, the server log is:

```
{ type: 'utf8', utf8Data: '{"command":"P"}' }
process
{ type: 'utf8',
  utf8Data: '{"command":"B","wall":{"length":2,"direction":"S"}}' }
sendMove
processHunter
{ type: 'utf8', utf8Data: '{"command":"W"}' }
process
process
{ type: 'utf8', utf8Data: '{"command":"D","wallIndex":0}' }
......
```
