### ISSUE TITLE
prey position

### ISSUE THREAD

**Issue by jfriend08** [brooklyn-omniheurists/evasion#18]
Hi, 
I think I should have the most updated version, and the prey position still cannot update?

Here are the commands:

```
socketP.send(JSON.stringify({command:'P'}));
socketP.send(JSON.stringify( {command:'M',direction: 'N'}) );
socketP.send(JSON.stringify({command:'P'}));
```

Then, below are the console.log, and I think there are two issues: 
1. no publisher's message
2. no position update for prey

```
Prey: {"command":"P","hunter":[0,0],"prey":[230,200]}
Prey: {"command":"P","hunter":[0,0],"prey":[230,200]}
```

**Comment by ylc265** [comment]
Hey if you look at the server.js code, I think they only update once both hunter and prey make their respective moves.

**Comment by ylc265** [comment]
mainly line 221

**Comment by jfriend08** [comment]
yea, thanks.
but then I did the following commands:

```
socketP.send(JSON.stringify({command:'P'}));
socketP.send(JSON.stringify( {command:'M',direction: 'N'}) );
socketH.send(JSON.stringify({command:'M'}));
socketP.send(JSON.stringify({command:'P'}));
```

and got the following:

```
Prey: {"command":"P","hunter":[1,1],"prey":[230,200]}
Publisher: {"hunter":[2,2],"prey":[230,200],"wall":[],"time":1,"gameover":false}
Prey: {"command":"P","hunter":[2,2],"prey":[230,200]}
```

Am I the only one got this issue?

**Comment by jfriend08** [comment]
nvm, it's because prey can only moved at next round
