### ISSUE TITLE
Case where the hunter bounces off his own wall

### ISSUE THREAD

**Issue by alexandresablayrolles** [brooklyn-omniheurists/evasion#19]
Can the hunter bounce off one of its own walls ?

Basically the hunter cannot change direction until it bounces off a wall. But the wall it creates never touch the diagonal line, along which the hunter is moving. At the end of the line (position (300, 300)), the hunter will bounce back and start moving up the diagonal ((299, 299), (298, 298), ...). I cannot figure out a situation where a hunter would bounce off a wall that it has created, since all these walls will be extra-diagonal.

**Comment by brooklyn-omniheurists** [comment]
@alexandresablayrolles You're on the money. Check the new readme c3c7025cd9815dee2781c55241e0cddd46a0485b  and be sure to pull the changes!

**Comment by alexandresablayrolles** [comment]
Excellent! Thanks
