### ISSUE TITLE
Running App.class and node server and test.html

### ISSUE THREAD

**Issue by mullachv** [brooklyn-omniheurists/evasion#20]
I run:
1-- node server.js
2-- App.class
3-- test.html

The Hunter message thread appears to be lost, not receiving any messages back after the first line below:
            client.connectToServer(hunter, cec, new URI(hunterEndpoint));
            messageLatch.await(100, TimeUnit.SECONDS);

Any suggestions, Architects?

**Comment by brooklyn-omniheurists** [comment]
81b29cd06bf6f1006c460cfae7cf7c08f76d319e should solve this issue!
