### ISSUE TITLE
Random Hunter move

### ISSUE THREAD

**Issue by mullachv** [brooklyn-omniheurists/evasion#21]
In reviewing the random ruby hunter moves, it appears the hunter keeps moving 'SE' at every step.
Is this something forced by the server? (notice hunter moves to 27,27; then 28,28...)

{"hunter":[27,27],"prey":[230,201],"walls":[{"length":251,"position":[1,1],"direction":"E"},{"length":38,"position":[11,11],"direction":"S"},{"length":269,"position":[25,25],"direction":"S"}],"time":27,"gameover":false,"errors":[]}
{"hunter":[28,28],"prey":[230,202],"walls":[{"length":251,"position":[1,1],"direction":"E"},{"length":38,"position":[11,11],"direction":"S"},{"length":269,"position":[25,25],"direction":"S"}],"time":28,"gameover":false,"errors":[]}
{"hunter":[29,29],"prey":[230,202],"walls":[{"length":251,"position":[1,1],"direction":"E"},{"length":38,"position":[11,11],"direction":"S"},{"length":269,"position":[25,25],"direction":"S"}],"time":29,"gameover":false,"errors":[]}
{"hunter":[30,30],"prey":[229,203],"walls":[{"length":251,"position":[1,1],"direction":"E"},{"length":38,"position":[11,11],"direction":"S"},{"length":269,"position":[25,25],"direction":"S"}],"time":30,"gameover":false,"errors":[]}

**Comment by mayanks43** [comment]
The hunter is like a ping-pong ball. It can't change directions until it bounces of a wall. Note this from the Problem Page -  
`H moves one unit (always diagonally or counter-diagonally based on its bounce history -- the hunter changes direction only when it encounters a wall).`

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 That's correct!
