### ISSUE TITLE
No walls in UI?

### ISSUE THREAD

**Issue by mayanks43** [brooklyn-omniheurists/evasion#25]
I am able to see the dots move in the UI but no walls.

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 I'll look into that.

**Comment by mayanks43** [comment]
The error is here: https://github.com/brooklyn-omniheurists/evasion/blob/master/evasion-ui/app/view1/view1.js#L33. curWall.direction is coming in as a tuple not a string. 

Also, it seems walls only go in one direction, whereas Professor wants it growing in both direction.

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 Yeah, that's coming up in the next release. Going to be a bit bigger since we'll have to change the API. Post thoughts on #8

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 As for walls being a tuple, we thought we fixed that, but if it's still an issue I will look into it.

**Comment by mayanks43** [comment]
@brooklyn-omniheurists Nope. I have the latest and not fixed.

**Comment by mayanks43** [comment]
@brooklyn-omniheurists [Here](https://gist.github.com/mayanks43/b53abe48ea69ec5851c8)'s some modifications to your ui code that allows to extend walls to the ends using the current API. So, obviously balls will go through walls unless you fix the API. Also, a lot of rewrite to remove unecessary loops.

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 Pull the latest code, that will send the proper string. And thanks for that, will look into that, I have some code set up for backwards compatibility I want to try as well.

**Comment by jfriend08** [comment]
Hi!
Just wondering is the UI part done? all I can see are just stuffs from angular-seed, but nothing specific to our evasion UI right?

**Comment by jfriend08** [comment]
Or, if there is any UI part that's working, can you show us where to find the readme to run? thx

**Comment by mayanks43** [comment]
The files are evasion-ui/app/view1. evasion-ui/app/app.css has some stylesheet code. But the main logic is in evasion-ui/app/view1/view1.js. To run the UI, type `npm start` when you are in the evasion-ui directory. The UI server connects to the pub-sub server, so you can start it anytime during the game.

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 Thanks for the assist!

Or you can just go to `localhost:8080/evasion-ui/app` after you do `node server.js`

**Comment by jfriend08** [comment]
thanks

**Comment by brooklyn-omniheurists** [comment]
There are walls in UI
