### ISSUE TITLE
Doubt: Do we have a time limit?

### ISSUE THREAD

**Issue by KshitizSethia** [brooklyn-omniheurists/evasion#26]
Hi,

Unlike other competitions, this one doesn't seem to have a time limit. Am I correct?

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia I think prof said verbally that we have a two minute limit, but I can't find any documentation to support that.

Currently the status is `¯\_(ツ)_/¯`

In all seriousness, we'll probably end up having to give a 2 minutes time interval, will ask prof.

**Comment by brooklyn-omniheurists** [comment]
2 minutes per player

If the Hunter runs out of time, he loses.
If the Prey runs out of time, his score is how many steps he survived.
