### ISSUE TITLE
Extra info in published data

### ISSUE THREAD

**Issue by ghost** [brooklyn-omniheurists/evasion#27]
Can we get the id-s of the walls in the published json data? Without id-s the list of walls in the json data not useful. Also the direction in which hunter is currently moving?

**Comment by brooklyn-omniheurists** [comment]
@tnvkrishna ok sounds good

**Comment by brooklyn-omniheurists** [comment]
@tnvkrishna Wall IDs are there!

**Comment by CodeOsiris** [comment]
Could you also update your readme? I did not see these in readme
