### ISSUE TITLE
Prey Misses First Publisher Message if connects second

### ISSUE THREAD

**Issue by keeyon2** [brooklyn-omniheurists/evasion#35]
## Suggestion

Can we have the first/all publisher messages only send if the webSocket with the
hunter player <----> publisher and the prey player <---> publisher are both connected? 

_A <----> B means A and B are connected via WebSocket_
### Problem Explained

For the first move, the hunter independently makes their move.  This is because the prey will only be making moves on even turns. 

If the hunter connects first we can have these events occur
1. Hunter Connects
2. Hunter Sends Publisher Move
3. Publisher receives move, updates info, sends out update to publisher webSocket - 
   **this will only be received by the hunter because the prey is not yet connected**
4. Prey Connects - _misses 1st publisher update_

This causes a problem in my code because the flow is orchestrated by the time variable, and when this happens prey gets its time out of synch.

Can we either have the publisher only send out its updates when both are connected, or can we have the Hunter and the Prey websocket also send out the time value when they are queried? 

**{"command":"t"} for time can also help.**

Would love to hear what others think.

**Comment by brooklyn-omniheurists** [comment]
@keeyon2 Sounds like a very reasonable request.

A quick workaround would be to check hunter's position, if its not (0,0), assume games started. This wont work in the case the hunter has moved back to it, but that only happens on reconnect which leads to the bigger issue.

If a disconnect occurs, the publisher should probably broadcast the latest state on reconnect, which means it'll also broadcast state on any connect, does that sound reasonable?

**Comment by keeyon2** [comment]
Good call.  I'll put that check in.  That will work.  Thanks for the recommendation
