### ISSUE TITLE
Nothing is displayed when opening test.html

### ISSUE THREAD

**Issue by CodeOsiris** [brooklyn-omniheurists/evasion#7]
The webpage I am seeing contains two buttons, looks like buttons for Prey, but there is no a map or buttons for the Hunter. I am using Chrome as my web browser, also tested on Firefox but same issue.

**Comment by brooklyn-omniheurists** [comment]
Check #1 
The test is just a client actually, check the inspector's output. 

EDIT: In the console of the inspector.

**Comment by mayanks43** [comment]
When do we get to see the UI?

**Comment by brooklyn-omniheurists** [comment]
We are closing in on polishing it up, stay tuned. The product launch is imminent.
