### ISSUE TITLE
Building wall

### ISSUE THREAD

**Issue by ghost** [brooklyn-omniheurists/evasion#8]
In readme it is written : "When a hunter builds a wall, it builds the wall at a point that touches the hunter, but not at the hunter." (any of the 4 neighbouring points?)
But in the problem description it is mentioned that "When H creates a wall, the wall must touch the point where H was before H moved. "

**Comment by KshitizSethia** [comment]
I think this is what it means. The hunter can place a wall (horizontal/vertical) only on the point it was last on. The exception is if wall touches the prey, then no wall.

**Comment by brooklyn-omniheurists** [comment]
That's right, don't forget walls have a thickness, so technically at the neighboring points the wall is touching the hunter. 

Think of it this way, if a hunter created two walls, NORTH and SOUTH and they both began at the point hunter was on before he moved, those walls would intersect.

**Comment by KshitizSethia** [comment]
This seems to be different from the game on dr ecco. Am I understanding this correct?

I can only place a wall in one direction (N/S/E/W) and place next one after a delay. So I would mostly not be able to build restricting areas (with no holes to go out of). The only time I can build a restricting area is when I'm about to collide with a wall, or have just reflected from a wall.

If the above is true, then the prey can always escape the hunter. ( I can say how, but let's confirm the above first)

**Comment by keeyon2** [comment]
I have a similar questions.  I am going to try to explain wall creation with an example through it with an example

# Problem

So lets say as a hunter, my immediate goal will be to build a vertical wall that spans the entire board.  I want my vertical wall to touch both the top and bottom edge of this 300 x 300 grid.

## Details
- Hunter Position before move: (150, 150)
- Direction: SE
- Grid currently has 0 walls
- Desire a wall that goes from (150, 0) to (150, 300).  _Vertical wall touching top and bottom of grid_
- We are on turn X

# Question

What kind of wall build is possible?

**Case 1:**  On turn X + 1, Hunter position will be (151, 151).  Can the hunter then build the vertical wall from (150, 0) to (150, 300) that spans the entire board. One space behind where the Hunter is?

**Or**

**Case 2:** On turn X, would hunter only be able to build a vertical wall North **or** South from its  (150, 150) position.

_This would mean a wall going North from (150, 149) to (150, 0)_ **or** _a wall South from (150, 151) to (150, 300)_

Which case is the correct wall building strategy?

**Comment by brooklyn-omniheurists** [comment]
@keeyon2 The second is correct, the wall build is either north or south, not both.

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia I'll have to update documentation, but now the walls are built at the position of hunter. You can build walls that extend from the point of the hunter to the wall, and since you get more moves as a hunter than the prey does, it only gives prey a small chance of escape.

**Comment by tnvkrishna** [comment]
@brooklyn-omniheurists Can the hunter also build a wall which starts from the point which is immediately to the north of the hunter, but extends to the west? this would mean that if the hunter was originally moving in the northwest direction, he would get reflected immediately.

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia Check the latest readme for wall building!

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia I noticed you mentioned Dr Ecco, we based it off the [code that was provided for us from the website](http://cs.nyu.edu/courses/fall15/CSCI-GA.2965-001/EvasionSource2013.zip) in case you were wondering. If prof says so otherwise, we will happily oblige.

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia @keeyon2 

Looks like times, they are a-changin. We'll try to update our new API and server to reflect this. Stay tuned.

**Comment by KshitizSethia** [comment]
@brooklyn-omniheurists haha! lots of turbulence! thank god we are all settled on case 1 from @keeyon2

**Comment by KshitizSethia** [comment]
@brooklyn-omniheurists one more change, now we might not need the "length" parameter in command B.

**Comment by brooklyn-omniheurists** [comment]
@KshitizSethia Exactly, we'll probably just take in a `V` or `H` parameter, and then automagically build the wall for you.

**Comment by jfriend08** [comment]
question:
so it can automatically building the wall across the place for you
how should I interpret the wall info from publisher like this:

```
 "position":[30,30],"direction":[1,0],"id":5
```

should I consider it as a H wall across (0,30) to (300,30)?

**Comment by brooklyn-omniheurists** [comment]
@jfriend08 

Not exactly. Recall some walls will be built on top of other walls!

``` json
{
  "position":[0,30],
  "direction":"E",
  "length": 300,
  "id":5
}
```

Will mean that this wall goes across horizontally. If theres another wall, a vertical wall, at point `[0,200]` going vertical, then the corresponding JSON for both would be:

``` json
{
  "position":[200,0],
  "direction":"S",
  "length": 300,
  "id":4
}
{
  "position":[0,30],
  "direction":"E",
  "length": 199,
  "id":5
}
```

**Comment by alexandresablayrolles** [comment]
Is the API call from the hunter using the "position" argument or the "V"/"H" then ?

**Comment by brooklyn-omniheurists** [comment]
@alexandresablayrolles That's the produce, not what the server consumes. We will accept the old way of doing things:

**API V0.1.0**

``` json
{
  "command" : "B",
  "wall": {
     "length": 10,
     "direction": "N"
   }
}
```

As well as the new method:

**API V0.2.0**:

``` json
{
  "command" : "B",
  "wall": {
     "direction": "H"
   }
}

{
  "command" : "B",
  "wall": {
     "direction": "V"
   }
}
```

Backwards compatible :+1: 

Coming in #28
